// AUTO-GENERATED by scripts/generate_perf_ci_main.py — do not edit by hand.

{
  // Array methods tests

  // push - adds elements to end, returns new length
  let arr = [1, 2, 3]
  let len = arr.push(4)
  console.log(len)
  console.log(arr.length)
  console.log(arr[3])

  arr.push(5, 6)
  console.log(arr.length)

  // pop - removes and returns last element
  let last = arr.pop()
  console.log(last)
  console.log(arr.length)

  // shift - removes and returns first element
  let first = arr.shift()
  console.log(first)
  console.log(arr.length)
  console.log(arr[0])

  // unshift - adds elements to beginning, returns new length
  let arr2 = [3, 4]
  let newLen = arr2.unshift(1, 2)
  console.log(newLen)
  console.log(arr2[0])
  console.log(arr2[1])

  // indexOf - returns index of element, or -1
  let nums = [10, 20, 30, 20]
  console.log(nums.indexOf(20))
  console.log(nums.indexOf(99))

  // includes - returns boolean
  console.log(nums.includes(30))
  console.log(nums.includes(99))

  // join - joins elements with separator
  let parts = ["a", "b", "c"]
  console.log(parts.join("-"))
  console.log(parts.join(""))
  console.log(parts.join())

  // reverse - reverses in place, returns array
  let rev = [1, 2, 3]
  rev.reverse()
  console.log(rev[0])
  console.log(rev[2])

  // slice - returns new array (non-mutating)
  let src = [1, 2, 3, 4, 5]
  let sl1 = src.slice(1, 3)
  console.log(sl1.length)
  console.log(sl1[0])
  console.log(sl1[1])

  // negative indices
  let sl2 = src.slice(-2)
  console.log(sl2.length)
  console.log(sl2[0])

  // concat - combines arrays
  let a1 = [1, 2]
  let a2 = [3, 4]
  let combined = a1.concat(a2)
  console.log(combined.length)
  console.log(combined[2])

  // concat with values
  let combined2 = a1.concat(5, [6, 7])
  console.log(combined2.length)

  // Empty array operations
  let empty = []
  console.log(empty.pop() ?? null)
  console.log(empty.shift() ?? null)
  console.log(empty.length)
}

{
  // Array methods performance test - intensive operations

  let iterations = 1000

  // Test push/pop performance
  let arr = []
  let i = 0
  while (i < iterations) {
      arr.push(i)
      i = i + 1
  }
  console.log(arr.length)

  while (arr.length > 0) {
      arr.pop()
  }
  console.log(arr.length)

  // Test shift/unshift (more expensive O(n))
  let arr2 = []
  i = 0
  let limit = 100
  while (i < limit) {
      arr2.unshift(i)
      i = i + 1
  }
  console.log(arr2.length)

  while (arr2.length > 0) {
      arr2.shift()
  }
  console.log(arr2.length)

  // Test indexOf/includes
  let searchArr = []
  i = 0
  while (i < 500) {
      searchArr.push(i)
      i = i + 1
  }

  let found = 0
  i = 0
  while (i < 100) {
      if (searchArr.includes(i * 5)) {
          found = found + 1
      }
      i = i + 1
  }
  console.log(found)

  // Test slice/concat
  let base = [1, 2, 3, 4, 5]
  let result = []
  i = 0
  while (i < 200) {
      let sliced = base.slice(1, 4)
      result = result.concat(sliced)
      i = i + 1
  }
  console.log(result.length)

  // Test join
  let words = ["hello", "world", "test", "array", "methods"]
  let joined = ""
  i = 0
  while (i < 200) {
      joined = words.join("-")
      i = i + 1
  }
  console.log(joined)

  // Test reverse
  let revArr = [1, 2, 3, 4, 5]
  i = 0
  while (i < 500) {
      revArr.reverse()
      i = i + 1
  }
  console.log(revArr[0])
}

{
  // Array manipulation stress tests
  // Tests array operations at scale to identify bottlenecks

  let start = 0;
  let end = 0;

  console.log("=== Array Stress Tests ===");
  console.log("");

  // === LARGE ARRAY CREATION ===
  console.log("--- Large Array Creation ---");

  start = Date.now();
  let arr100 = [];
  for (let i = 0; i < 100; i++) {
      arr100.push(i);
  }
  end = Date.now();
  console.log("Build 100-elem array (push): " + (end - start) + "ms");

  start = Date.now();
  let arr1000 = [];
  for (let i = 0; i < 1000; i++) {
      arr1000.push(i);
  }
  end = Date.now();
  console.log("Build 1000-elem array (push): " + (end - start) + "ms");

  start = Date.now();
  let arr5000 = [];
  for (let i = 0; i < 5000; i++) {
      arr5000.push(i);
  }
  end = Date.now();
  console.log("Build 5000-elem array (push): " + (end - start) + "ms");

  // === ARRAY ITERATION ===
  console.log("");
  console.log("--- Array Iteration ---");

  start = Date.now();
  let sum1 = 0;
  for (let i = 0; i < arr1000.length; i++) {
      sum1 = sum1 + arr1000[i];
  }
  end = Date.now();
  console.log("for-i loop 1000 elems: " + (end - start) + "ms (sum=" + sum1 + ")");

  start = Date.now();
  let sum2 = 0;
  for (let item of arr1000) {
      sum2 = sum2 + item;
  }
  end = Date.now();
  console.log("for-of loop 1000 elems: " + (end - start) + "ms");

  start = Date.now();
  let sum3 = 0;
  arr1000.forEach(x => { sum3 = sum3 + x; });
  end = Date.now();
  console.log("forEach 1000 elems: " + (end - start) + "ms");

  // === MAP/FILTER/REDUCE ===
  console.log("");
  console.log("--- Map/Filter/Reduce ---");

  start = Date.now();
  let mapped = arr1000.map(x => x * 2);
  end = Date.now();
  console.log("map 1000 elems: " + (end - start) + "ms");

  start = Date.now();
  let filtered = arr1000.filter(x => x % 2 === 0);
  end = Date.now();
  console.log("filter 1000 elems: " + (end - start) + "ms");

  start = Date.now();
  let reduced = arr1000.reduce((acc, x) => acc + x, 0);
  end = Date.now();
  console.log("reduce 1000 elems: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 100; i++) {
      arr100.map(x => x * 2);
  }
  end = Date.now();
  console.log("map 100 elems x100: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 100; i++) {
      arr100.filter(x => x > 50);
  }
  end = Date.now();
  console.log("filter 100 elems x100: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 100; i++) {
      arr100.reduce((a, x) => a + x, 0);
  }
  end = Date.now();
  console.log("reduce 100 elems x100: " + (end - start) + "ms");

  // === CHAINED OPERATIONS ===
  console.log("");
  console.log("--- Chained Operations ---");

  start = Date.now();
  let result1 = arr100
      .map(x => x * 2)
      .filter(x => x > 50)
      .map(x => x + 1);
  end = Date.now();
  console.log("map-filter-map chain: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 50; i++) {
      arr100
          .filter(x => x % 2 === 0)
          .map(x => x * 3)
          .reduce((a, x) => a + x, 0);
  }
  end = Date.now();
  console.log("filter-map-reduce x50: " + (end - start) + "ms");

  // === SORTING ===
  console.log("");
  console.log("--- Sorting ---");

  function shuffle(arr) {
      let result = [...arr];
      for (let i = result.length - 1; i > 0; i--) {
          let j = Math.floor(Math.random() * (i + 1));
          let temp = result[i];
          result[i] = result[j];
          result[j] = temp;
      }
      return result;
  }

  start = Date.now();
  for (let i = 0; i < 100; i++) {
      let toSort = shuffle(arr100);
      toSort.sort((a, b) => a - b);
  }
  end = Date.now();
  console.log("sort 100 elems x100: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 20; i++) {
      let toSort = shuffle(arr1000);
      toSort.sort((a, b) => a - b);
  }
  end = Date.now();
  console.log("sort 1000 elems x20: " + (end - start) + "ms");

  // === FIND/INCLUDES/INDEXOF ===
  console.log("");
  console.log("--- Search Operations ---");

  start = Date.now();
  for (let i = 0; i < 500; i++) {
      arr1000.find(x => x === 500);
  }
  end = Date.now();
  console.log("find middle (1000 elems x500): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 500; i++) {
      arr1000.includes(500);
  }
  end = Date.now();
  console.log("includes middle (1000 elems x500): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 500; i++) {
      arr1000.indexOf(500);
  }
  end = Date.now();
  console.log("indexOf middle (1000 elems x500): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 500; i++) {
      arr1000.some(x => x > 500);
  }
  end = Date.now();
  console.log("some (1000 elems x500): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 500; i++) {
      arr1000.every(x => x < 2000);
  }
  end = Date.now();
  console.log("every (1000 elems x500): " + (end - start) + "ms");

  // === SPLICE/SLICE ===
  console.log("");
  console.log("--- Splice/Slice ---");

  start = Date.now();
  for (let i = 0; i < 1000; i++) {
      let copy = [...arr100];
      copy.splice(50, 0, 999);
  }
  end = Date.now();
  console.log("splice insert (100 elems x1000): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 1000; i++) {
      let copy = [...arr100];
      copy.splice(50, 1);
  }
  end = Date.now();
  console.log("splice delete (100 elems x1000): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 1000; i++) {
      arr100.slice(25, 75);
  }
  end = Date.now();
  console.log("slice (100 elems x1000): " + (end - start) + "ms");

  // === CONCAT/SPREAD ===
  console.log("");
  console.log("--- Concat/Spread ---");

  let a50 = arr100.slice(0, 50);
  let b50 = arr100.slice(50, 100);

  start = Date.now();
  for (let i = 0; i < 1000; i++) {
      a50.concat(b50);
  }
  end = Date.now();
  console.log("concat 50+50 x1000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 1000; i++) {
      [...a50, ...b50];
  }
  end = Date.now();
  console.log("spread 50+50 x1000: " + (end - start) + "ms");

  // === FLAT/FLATMAP ===
  console.log("");
  console.log("--- Flat/FlatMap ---");

  let nested = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]];
  start = Date.now();
  for (let i = 0; i < 2000; i++) {
      nested.flat();
  }
  end = Date.now();
  console.log("flat (5x2) x2000: " + (end - start) + "ms");

  // Match Tish test: map + flat
  start = Date.now();
  for (let i = 0; i < 500; i++) {
      arr100.map(x => [x, x * 2]).flat();
  }
  end = Date.now();
  console.log("map+flat (100 elems) x500: " + (end - start) + "ms");

  // === ARRAY OF OBJECTS ===
  console.log("");
  console.log("--- Array of Objects ---");

  let users = [];
  for (let i = 0; i < 100; i++) {
      users.push({ id: i, name: "user" + i, active: i % 3 === 0 });
  }

  start = Date.now();
  for (let i = 0; i < 200; i++) {
      users.filter(u => u.active);
  }
  end = Date.now();
  console.log("filter objects (100 objs x200): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 200; i++) {
      users.map(u => u.name);
  }
  end = Date.now();
  console.log("map to property (100 objs x200): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 200; i++) {
      users.find(u => u.id === 50);
  }
  end = Date.now();
  console.log("find by property (100 objs x200): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 50; i++) {
      users.sort((a, b) => a.id - b.id);
  }
  end = Date.now();
  console.log("sort by property (100 objs x50): " + (end - start) + "ms");

  console.log("");
  console.log("=== Array Stress Tests Complete ===");
}

{
  // MVP test: arrays and indexing (JS equivalent of arrays.tish)
  const arr = [1, 2, 3];
  console.log(arr[0]);
  console.log(arr[1]);
  console.log(arr[2]);
  let sum = 0;
  for (let i = 0; i < 3; i = i + 1)
    sum = sum + arr[i];
  console.log("sum:", sum);
  const nested = [[1, 2], [3, 4]];
  console.log(nested[0][1]);
  console.log(nested[1][0]);
}

{
  // Test arrow function syntax

  let nums = [1, 2, 3, 4, 5];

  // Single param, expression body
  let doubled = nums.map(x => x * 2);
  console.log("doubled:", doubled.join(","));

  // Multiple params with parentheses
  let sum = nums.reduce((acc, x) => acc + x, 0);
  console.log("sum:", sum);

  // Arrow with empty params
  let getHello = () => "Hello";
  console.log(getHello());

  // Arrow with block body
  let process = (x) => {
      let y = x * 2;
      return y + 1;
  };
  console.log("process(5):", process(5));

  // Filter with arrow
  let evens = nums.filter(n => n % 2 === 0);
  console.log("evens:", evens.join(","));

  // Arrow functions in chaining
  let result = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      .filter(x => x % 2 === 0)
      .map(x => x * x)
      .filter(x => x > 20);
  console.log("chained:", result.join(","));

  // Direct arrow call
  let add = (a, b) => a + b;
  console.log("add(5, 3):", add(5, 3));

  // Arrow with object param
  let people = [
      { name: "Alice", age: 25 },
      { name: "Bob", age: 30 },
      { name: "Charlie", age: 20 }
  ];
  function getName(p) { return p.name; }
  let names = people.map(getName);
  console.log("names:", names.join(","));

  // Sort simulation with find
  function isOldest(p) { return p.age === 30; }
  let oldest = people.find(isOldest);
  console.log("oldest:", oldest.name);
}

{
  // Granular benchmark: measure individual operation costs
  // Each section tests one specific feature with 5000 iterations

  let iterations = 5000;
  let start = 0;
  let end = 0;

  console.log("=== Granular Operation Benchmarks ===");
  console.log("Iterations per test: " + iterations);
  console.log("");

  // === ARITHMETIC ===
  console.log("--- Arithmetic ---");

  start = Date.now();
  let sum = 0;
  for (let i = 0; i < iterations; i++) {
      sum = sum + i * 2 - 1;
  }
  end = Date.now();
  console.log("Basic math (+, *, -): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let x = i ** 2;
  }
  end = Date.now();
  console.log("Exponentiation (**): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let x = i % 17;
  }
  end = Date.now();
  console.log("Modulo (%): " + (end - start) + "ms");

  // === VARIABLE ACCESS ===
  console.log("");
  console.log("--- Variable Access ---");

  let outerVar = 42;
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let x = outerVar;
  }
  end = Date.now();
  console.log("Local var read: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      outerVar = i;
  }
  end = Date.now();
  console.log("Local var write: " + (end - start) + "ms");

  // === FUNCTION CALLS ===
  console.log("");
  console.log("--- Function Calls ---");

  let simpleFunc = () => 42;
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      simpleFunc();
  }
  end = Date.now();
  console.log("Empty arrow fn call: " + (end - start) + "ms");

  let add = (a, b) => a + b;
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      add(i, 1);
  }
  end = Date.now();
  console.log("Arrow fn with args: " + (end - start) + "ms");

  function namedFunc(n) {
      return n + 1;
  }
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      namedFunc(i);
  }
  end = Date.now();
  console.log("Named fn call: " + (end - start) + "ms");

  // === NESTED FUNCTIONS ===
  console.log("");
  console.log("--- Nested Functions ---");

  function outerWithHelper(n) {
      function helper(x) {
          return x * 2 + n;
      }
      return helper(n) + helper(n + 1);
  }
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      outerWithHelper(i);
  }
  end = Date.now();
  console.log("Nested fn call: " + (end - start) + "ms");

  function deepNested(a) {
      function level2(b) {
          function level3(c) {
              return a + b + c;
          }
          return level3(3);
      }
      return level2(2);
  }
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      deepNested(i);
  }
  end = Date.now();
  console.log("3-level nested fn: " + (end - start) + "ms");

  // === OBJECT CREATION ===
  console.log("");
  console.log("--- Object Creation ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let obj = { a: 1 };
  }
  end = Date.now();
  console.log("Create 1-prop object: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let obj = { a: 1, b: 2, c: 3, d: 4, e: 5 };
  }
  end = Date.now();
  console.log("Create 5-prop object: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let obj = { a: i, b: i + 1, c: i + 2 };
  }
  end = Date.now();
  console.log("Create object with exprs: " + (end - start) + "ms");

  // === OBJECT ACCESS ===
  console.log("");
  console.log("--- Object Access ---");

  let testObj = { x: 1, y: 2, z: 3, w: 4 };
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let v = testObj.x;
  }
  end = Date.now();
  console.log("Dot property read: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      testObj.x = i;
  }
  end = Date.now();
  console.log("Dot property write: " + (end - start) + "ms");

  let key = "y";
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let v = testObj[key];
  }
  end = Date.now();
  console.log("Bracket property read: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      testObj[key] = i;
  }
  end = Date.now();
  console.log("Bracket property write: " + (end - start) + "ms");

  // Deep access
  let deep = { a: { b: { c: { d: 42 } } } };
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let v = deep.a.b.c.d;
  }
  end = Date.now();
  console.log("Deep property chain (4): " + (end - start) + "ms");

  // === ARRAY CREATION ===
  console.log("");
  console.log("--- Array Creation ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3];
  }
  end = Date.now();
  console.log("Create 3-elem array: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  }
  end = Date.now();
  console.log("Create 10-elem array: " + (end - start) + "ms");

  // === ARRAY ACCESS ===
  console.log("");
  console.log("--- Array Access ---");

  let testArr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let v = testArr[5];
  }
  end = Date.now();
  console.log("Array index read: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      testArr[5] = i;
  }
  end = Date.now();
  console.log("Array index write: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let len = testArr.length;
  }
  end = Date.now();
  console.log("Array .length: " + (end - start) + "ms");

  // === ARRAY METHODS ===
  console.log("");
  console.log("--- Array Methods ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3];
      arr.push(4);
  }
  end = Date.now();
  console.log("Array.push(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4];
      arr.pop();
  }
  end = Date.now();
  console.log("Array.pop(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [3, 1, 4, 1, 5];
      arr.sort((a, b) => a - b);
  }
  end = Date.now();
  console.log("Array.sort() (5 elems): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4, 5];
      arr.map(x => x * 2);
  }
  end = Date.now();
  console.log("Array.map() (5 elems): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4, 5];
      arr.filter(x => x > 2);
  }
  end = Date.now();
  console.log("Array.filter() (5 elems): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4, 5];
      arr.reduce((acc, x) => acc + x, 0);
  }
  end = Date.now();
  console.log("Array.reduce() (5 elems): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4, 5];
      arr.splice(2, 1, 99);
  }
  end = Date.now();
  console.log("Array.splice(): " + (end - start) + "ms");

  // === SPREAD OPERATORS ===
  console.log("");
  console.log("--- Spread Operators ---");

  let srcArr = [1, 2, 3];
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [...srcArr];
  }
  end = Date.now();
  console.log("Array spread copy: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [...srcArr, 4, 5];
  }
  end = Date.now();
  console.log("Array spread + concat: " + (end - start) + "ms");

  let srcObj = { a: 1, b: 2 };
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let obj = { ...srcObj };
  }
  end = Date.now();
  console.log("Object spread copy: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let obj = { ...srcObj, c: 3 };
  }
  end = Date.now();
  console.log("Object spread + extend: " + (end - start) + "ms");

  // === DESTRUCTURING ===
  console.log("");
  console.log("--- Destructuring ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let [a, b, c] = [1, 2, 3];
  }
  end = Date.now();
  console.log("Array destructure (3): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let { x, y } = { x: 1, y: 2 };
  }
  end = Date.now();
  console.log("Object destructure (2): " + (end - start) + "ms");

  // === OBJECT STATICS ===
  console.log("");
  console.log("--- Object Statics ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let target = { a: 1 };
      Object.assign(target, { b: 2 });
  }
  end = Date.now();
  console.log("Object.assign(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      Object.keys({ a: 1, b: 2, c: 3 });
  }
  end = Date.now();
  console.log("Object.keys(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      Object.values({ a: 1, b: 2, c: 3 });
  }
  end = Date.now();
  console.log("Object.values(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      Object.entries({ a: 1, b: 2, c: 3 });
  }
  end = Date.now();
  console.log("Object.entries(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      Object.fromEntries([["a", 1], ["b", 2]]);
  }
  end = Date.now();
  console.log("Object.fromEntries(): " + (end - start) + "ms");

  // === LOOPS ===
  console.log("");
  console.log("--- Loops ---");

  start = Date.now();
  for (let outer = 0; outer < 100; outer++) {
      for (let i = 0; i < 50; i++) {
          let x = i;
      }
  }
  end = Date.now();
  console.log("for loop (100x50): " + (end - start) + "ms");

  start = Date.now();
  for (let outer = 0; outer < 100; outer++) {
      let i = 0;
      while (i < 50) {
          let x = i;
          i++;
      }
  }
  end = Date.now();
  console.log("while loop (100x50): " + (end - start) + "ms");

  let loopArr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  start = Date.now();
  for (let outer = 0; outer < iterations / 10; outer++) {
      for (let item of loopArr) {
          let x = item;
      }
  }
  end = Date.now();
  console.log("for-of loop (500x10): " + (end - start) + "ms");

  // === CONDITIONALS ===
  console.log("");
  console.log("--- Conditionals ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      if (i % 2 === 0) {
          let x = 1;
      } else {
          let x = 2;
      }
  }
  end = Date.now();
  console.log("if-else: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let x = i % 2 === 0 ? 1 : 2;
  }
  end = Date.now();
  console.log("ternary: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let val = i % 4;
      switch (val) {
          case 0: break;
          case 1: break;
          case 2: break;
          default: break;
      }
  }
  end = Date.now();
  console.log("switch (4 cases): " + (end - start) + "ms");

  // === STRING OPERATIONS ===
  console.log("");
  console.log("--- String Operations ---");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let s = "hello" + " " + "world";
  }
  end = Date.now();
  console.log("String concat (+): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let s = `hello ${i}`;
  }
  end = Date.now();
  console.log("Template literal: " + (end - start) + "ms");

  let testStr = "hello world";
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let len = testStr.length;
  }
  end = Date.now();
  console.log("String.length: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      testStr.toUpperCase();
  }
  end = Date.now();
  console.log("String.toUpperCase(): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      testStr.split(" ");
  }
  end = Date.now();
  console.log("String.split(): " + (end - start) + "ms");

  console.log("");
  console.log("=== Granular Benchmarks Complete ===");
}

{
  // MVP test: bitwise operators & | ^ ~ << >>
  const a = 12;
  const b = 5;
  console.log("12 & 5 =", a & b);
  console.log("12 | 5 =", a | b);
  console.log("12 ^ 5 =", a ^ b);
  console.log("~0 =", ~0);
  console.log("1 << 4 =", 1 << 4);
  console.log("16 >> 2 =", 16 >> 2);
}

{
  // MVP test: break and continue in nested loops (JS equivalent of break_continue.tish)
  let found = 0;
  for (let i = 0; i < 3; i = i + 1) {
    for (let j = 0; j < 3; j = j + 1) {
      if (j === 1)
        continue;
      found = found + 1;
      if (i === 2 && j === 2)
        break;
    }
  }
  console.log("found:", found);
  let count = 0;
  for (let i = 0; i < 5; i = i + 1) {
    if (i === 3)
      break;
    count = count + 1;
  }
  console.log("count:", count);
}

{
  // MVP test: parseInt, parseFloat, isFinite, isNaN, Infinity, NaN (JS equivalent of builtins.tish)
  console.log(parseInt("42"));
  console.log(parseInt("  -123  "));
  console.log(parseInt("3.14"));
  console.log(parseFloat("3.14"));
  console.log(parseFloat("  -2.5  "));
  console.log(isFinite(1));
  console.log(isFinite(Infinity));
  console.log(isFinite(NaN));
  console.log(isNaN(NaN));
  console.log(isNaN(1));
  console.log(Infinity);
  console.log(NaN);
  console.log(typeof Infinity);
  console.log(typeof NaN);
}

{
  // MVP test: compound assignment operators (+=, -=, *=, /=, %=) - JS equivalent

  // Basic compound assignment
  let x = 10;
  x += 5;
  console.log("10 += 5:", x);

  x -= 3;
  console.log("15 -= 3:", x);

  x *= 2;
  console.log("12 *= 2:", x);

  x /= 4;
  console.log("24 /= 4:", x);

  x %= 4;
  console.log("6 %= 4:", x);

  // String concatenation with +=
  let s = "Hello";
  s += " ";
  s += "World";
  console.log(s);

  // Compound assignment in loops
  let sum = 0;
  for (let i = 0; i < 5; i++) {
    sum += i;
  }
  console.log("sum 0..4:", sum);

  // Compound assignment with expressions
  let a = 10;
  let b = 3;
  a += b * 2;
  console.log("10 += (3*2):", a);

  // Chained compound (right-to-left evaluation)
  let p = 5;
  let q = 10;
  p += q -= 2;
  console.log("q after q -= 2:", q);
  console.log("p after p += q:", p);

  // Compound with negatives
  let n = 20;
  n -= 25;
  console.log("20 -= 25:", n);

  // Division and modulo edge cases
  let d = 17;
  d /= 3;
  console.log("17 / 3:", d);

  let m = 17;
  m %= 3;
  console.log("17 % 3:", m);
}

{
  // MVP test: conditional (ternary) operator (JS equivalent of conditional.tish)
  let a = 1;
  let b = 2;
  console.log(a > b ? "bigger" : "smaller");
  console.log(a < b ? "smaller" : "bigger");
  console.log(a === 1 ? 100 : 200);
  console.log(null ? "yes" : "no");
  console.log(true ? "t" : "f");
  console.log(false ? "t" : "f");
}

{
  // MVP test: const declarations (JS equivalent)

  // Basic const
  const x = 10;
  console.log("x:", x);

  // const with different types
  const s = "hello";
  const b = true;
  const n = null;
  const arr = [1, 2, 3];
  const obj = { a: 1 };

  console.log("s:", s);
  console.log("b:", b);
  console.log("n:", n);
  console.log("arr:", arr[0], arr[1], arr[2]);
  console.log("obj.a:", obj.a);

  // const in blocks
  if (true) {
    const inner = 42;
    console.log("inner:", inner);
  }

  // const in for-of (each iteration gets new binding)
  const items = ["a", "b", "c"];
  for (const item of items) {
    console.log("item:", item);
  }

  // let vs const (let can be reassigned)
  let mutable = 1;
  mutable = 2;
  console.log("mutable:", mutable);

  // const function (function declarations are mutable by default)
  function greet(name) {
    return "Hello, " + name;
  }
  console.log(greet("Universe"));
}

{
  // MVP test: do-while loop (JS equivalent of do_while.tish)
  let i = 0;
  do {
    console.log(i);
    i = i + 1;
  } while (i < 3);
  console.log("done");
}

{
  // MVP test: exponentiation operator ** (JS equivalent of exponentiation.tish)
  console.log(2 ** 3);
  console.log(2 ** 10);
  console.log(4 ** 0.5);
  console.log(2 ** 3 ** 2);
}

{
  // MVP test: fun and any (JS equivalent of fun_any.tish)
  function double(x) { return x * 2; }
  function add(a, b) { return a + b; }
  const a = 10;
  const b = 20;
  console.log("double", a, "=", double(a));
  console.log("add", a, b, "=", add(a, b));
  function greet(name) {
    console.log("Hello,", name);
    return null;
  }
  greet("Tish");
}

{
  // MVP test: for-of loop (iterate arrays and strings)
  const arr = [10, 20, 30];
  let sum = 0;
  for (const x of arr)
    sum = sum + x;
  console.log("array sum:", sum);

  const s = "abc";
  for (const c of s)
    console.log("char:", c);
}

{
  // Test higher-order array methods

  let nums = [1, 2, 3, 4, 5];

  // Define callback functions
  function double(x) { return x * 2; }
  function isEven(x) { return x % 2 === 0; }
  function add(acc, x) { return acc + x; }
  function gtThree(x) { return x > 3; }
  function gtZero(x) { return x > 0; }
  function isThree(x) { return x === 3; }
  function ltThree(x) { return x < 3; }

  // map
  let doubled = nums.map(double);
  console.log("map:", doubled.join(","));

  // filter
  let evens = nums.filter(isEven);
  console.log("filter:", evens.join(","));

  // reduce with initial value
  let sum = nums.reduce(add, 0);
  console.log("reduce:", sum);

  // reduce without initial value
  let product = nums.reduce(function(acc, x) { return acc * x; });
  console.log("reduce (no init):", product);

  // find
  let found = nums.find(gtThree);
  console.log("find:", found);

  // find returns undefined when not found (we'll use null in output)
  let notFound = nums.find(function(x) { return x > 100; });
  console.log("find (not found):", notFound === undefined ? "null" : notFound);

  // findIndex
  let foundIdx = nums.findIndex(gtThree);
  console.log("findIndex:", foundIdx);

  // findIndex returns -1 when not found
  let notFoundIdx = nums.findIndex(function(x) { return x > 100; });
  console.log("findIndex (not found):", notFoundIdx);

  // some
  console.log("some (> 3):", nums.some(gtThree));
  console.log("some (> 100):", nums.some(function(x) { return x > 100; }));

  // every
  console.log("every (> 0):", nums.every(gtZero));
  console.log("every (> 3):", nums.every(gtThree));

  // forEach
  let total = 0;
  function addToTotal(x) { total = total + x; }
  nums.forEach(addToTotal);
  console.log("forEach total:", total);

  // flat
  let nested = [1, [2, 3], [4, [5, 6]]];
  let flat1 = nested.flat();
  let flat1Str = flat1.map(x => Array.isArray(x) ? "[" + x.join(", ") + "]" : x).join(",");
  console.log("flat(1):", flat1Str);
  console.log("flat(2):", nested.flat(2).join(","));

  // Chaining
  let result = [1, 2, 3, 4, 5, 6]
      .filter(isEven)
      .map(double);
  console.log("chained:", result.join(","));
}

{
  // MVP perf: in operator
  const o = { a: 1, b: 2 };
  console.log("a" in o);
  console.log("b" in o);
  console.log("c" in o);

  const arr = [10, 20, 30];
  console.log(0 in arr);
  console.log(2 in arr);
  console.log(3 in arr);
  console.log("length" in arr);
}

{
  // MVP test: postfix and prefix ++ and -- (JS equivalent of inc_dec.tish)
  let a = 5;
  console.log(a++);
  console.log(a);
  let b = 10;
  console.log(b--);
  console.log(b);
  let c = 3;
  console.log(++c);
  console.log(c);
  let d = 7;
  console.log(--d);
  console.log(d);
}

{
  // MVP perf: JSON.parse and JSON.stringify
  const obj = { x: 1, y: "hi", z: true };
  const s = JSON.stringify(obj);
  console.log(s);

  const parsed = JSON.parse(s);
  console.log(parsed.x);
  console.log(parsed.y);
  console.log(parsed.z);

  const arr = [1, 2, "a"];
  console.log(JSON.stringify(arr));

  const arr2 = JSON.parse('[1,2,"a"]');
  console.log(arr2[0]);
  console.log(arr2[1]);
  console.log(arr2[2]);
}

{
  // MVP test: .length property on arrays and strings
  const arr = [10, 20, 30, 40];
  console.log("array length:", arr.length);
  const s = "hello";
  console.log("string length:", s.length);
  console.log("empty array:", [].length);
  console.log("empty string:", "".length);
}

{
  // MVP test: Math builtins (JS equivalent of math.tish)
  console.log(Math.abs(-5));
  console.log(Math.abs(5));
  console.log(Math.sqrt(4));
  console.log(Math.sqrt(2));
  console.log(Math.min(1, 2, 3));
  console.log(Math.max(1, 2, 3));
  console.log(Math.min(5));
  console.log(Math.max(5));
  console.log(Math.floor(3.7));
  console.log(Math.ceil(3.2));
  console.log(Math.round(3.5));
  console.log(Math.round(3.2));
}

{
  // Test property and index assignment (mutation)

  // Object property assignment
  let obj = { x: 1, y: 2 };
  console.log(obj.x);
  obj.x = 10;
  console.log(obj.x);

  // Add new property
  obj.z = 30;
  console.log(obj.z);

  // Nested object assignment
  let nested = { a: { b: 1 } };
  nested.a.b = 42;
  console.log(nested.a.b);

  // Array index assignment
  let arr = [1, 2, 3];
  console.log(arr[1]);
  arr[1] = 20;
  console.log(arr[1]);

  // Extend array with assignment (JS behavior)
  arr[5] = 100;
  console.log(arr.length);
  console.log(arr[5]);
  console.log(arr[4]); // undefined in JS, null in Tish

  // Object bracket notation assignment
  let data = {};
  data["key"] = "value";
  console.log(data.key);

  // Numeric key on object
  data[42] = "answer";
  console.log(data["42"]);

  // Mixed mutations
  let counter = { count: 0 };
  counter.count = counter.count + 1;
  console.log(counter.count);
  counter.count = counter.count + 5;
  console.log(counter.count);

  // Array of objects
  let items = [{ name: "a" }, { name: "b" }];
  items[0].name = "updated";
  console.log(items[0].name);

  // Function returning object, then mutate
  function makeObj() {
      return { val: 0 };
  }
  let result = makeObj();
  result.val = 999;
  console.log(result.val);
}

{
  // Complex nested loops, scopes, and functions test

  // === NESTED LOOPS ===

  // Triple nested for loops - matrix traversal
  let sum = 0;
  for (let i = 0; i < 3; i = i + 1) {
      for (let j = 0; j < 3; j = j + 1) {
          for (let k = 0; k < 3; k = k + 1) {
              sum = sum + (i * 9 + j * 3 + k);
          }
      }
  }
  console.log("Triple nested sum:", sum);

  // Mixed loop types nested
  let result = 0;
  let outer = 0;
  while (outer < 3) {
      for (let mid = 0; mid < 3; mid = mid + 1) {
          let inner = 0;
          while (inner < 3) {
              result = result + 1;
              inner = inner + 1;
          }
      }
      outer = outer + 1;
  }
  console.log("Mixed loops count:", result);

  // Nested for-of loops
  let matrix = [[1, 2], [3, 4], [5, 6]];
  let matrixSum = 0;
  for (let row of matrix) {
      for (let cell of row) {
          matrixSum = matrixSum + cell;
      }
  }
  console.log("Matrix sum:", matrixSum);

  // Nested loops with break/continue
  let breakSum = 0;
  for (let i = 0; i < 5; i = i + 1) {
      for (let j = 0; j < 5; j = j + 1) {
          if (j === 3) {
              continue;
          }
          if (i === 3 && j === 2) {
              break;
          }
          breakSum = breakSum + 1;
      }
  }
  console.log("Break/continue sum:", breakSum);

  // === NESTED SCOPES ===

  // Variable shadowing across scopes
  let x = 1;
  {
      let x = 2;
      {
          let x = 3;
          {
              let x = 4;
              console.log("Innermost x:", x);
          }
          console.log("Third level x:", x);
      }
      console.log("Second level x:", x);
  }
  console.log("Outer x:", x);

  // Accessing outer scope variables
  let a = 10;
  let b = 20;
  {
      let c = a + b;
      {
          let d = c + a;
          {
              let e = d + b + c;
              console.log("Deep access:", e);
          }
      }
  }

  // Scope with loops
  let loopScoped = 0;
  for (let i = 0; i < 3; i = i + 1) {
      let blockVar = i * 10;
      {
          let innerVar = blockVar + i;
          loopScoped = loopScoped + innerVar;
      }
  }
  console.log("Loop scoped:", loopScoped);

  // === NESTED FUNCTIONS ===

  // Simple nested function
  function outerFunc(n) {
      function inner(m) {
          return m * 2;
      }
      return inner(n) + n;
  }
  console.log("Nested func:", outerFunc(5));

  // Nested function accessing outer scope (called within parent)
  function computeWithHelper(base, multiplier) {
      function helper(x) {
          return base + (x * multiplier);
      }
      let r1 = helper(1);
      let r2 = helper(2);
      let r3 = helper(3);
      return r1 + r2 + r3;
  }
  console.log("Helper result:", computeWithHelper(10, 5));

  // Multiple levels of nested functions
  function level1(a) {
      function level2(b) {
          function level3(c) {
              function level4(d) {
                  return a + b + c + d;
              }
              return level4(4);
          }
          return level3(3);
      }
      return level2(2);
  }
  console.log("4 level nesting:", level1(1));

  // Recursive nested function
  function fibonacci(n) {
      function fib(a, b, remaining) {
          if (remaining === 0) {
              return a;
          }
          return fib(b, a + b, remaining - 1);
      }
      return fib(0, 1, n);
  }
  console.log("Fib 10:", fibonacci(10));

  // Mutually referencing nested functions
  function isEvenOdd(n) {
      function isEven(x) {
          if (x === 0) return true;
          return isOdd(x - 1);
      }
      function isOdd(x) {
          if (x === 0) return false;
          return isEven(x - 1);
      }
      return isEven(n);
  }
  console.log("Is 10 even?", isEvenOdd(10));
  console.log("Is 7 even?", isEvenOdd(7));

  // === COMBINED: LOOPS + SCOPES + FUNCTIONS ===

  // Function with nested loops and scopes
  function processMatrix(mat) {
      let total = 0;
      for (let row of mat) {
          let rowSum = 0;
          {
              for (let val of row) {
                  rowSum = rowSum + val;
              }
          }
          total = total + rowSum;
      }
      return total;
  }
  console.log("Process matrix:", processMatrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]));

  // Function with nested helper called in loop
  function sumWithTransform(arr, offset) {
      function transform(val) {
          return val * 2 + offset;
      }
      let total = 0;
      for (let item of arr) {
          total = total + transform(item);
      }
      return total;
  }
  console.log("Transform sum:", sumWithTransform([1, 2, 3, 4, 5], 10));

  // Complex accumulator with nested everything
  function complexAccumulator(data) {
      let result = 0;
      
      function processItem(item) {
          let itemResult = 0;
          if (typeof item === "number") {
              return item;
          }
          for (let subItem of item) {
              {
                  let processed = processItem(subItem);
                  itemResult = itemResult + processed;
              }
          }
          return itemResult;
      }
      
      for (let item of data) {
          {
              let contribution = processItem(item);
              result = result + contribution;
          }
      }
      return result;
  }
  console.log("Complex accum:", complexAccumulator([1, [2, 3], [[4, 5], 6], 7]));

  // Nested conditionals with scopes
  function nestedConditional(x) {
      let result = "none";
      if (x > 0) {
          let sign = "positive";
          if (x > 10) {
              let size = "large";
              if (x > 100) {
                  result = sign + "-" + size + "-huge";
              } else {
                  result = sign + "-" + size;
              }
          } else {
              result = sign + "-small";
          }
      } else {
          if (x < 0) {
              result = "negative";
          } else {
              result = "zero";
          }
      }
      return result;
  }
  console.log("Cond 0:", nestedConditional(0));
  console.log("Cond 5:", nestedConditional(5));
  console.log("Cond 50:", nestedConditional(50));
  console.log("Cond 150:", nestedConditional(150));
  console.log("Cond -5:", nestedConditional(-5));

  // Performance stress: deeply nested computation
  function deepCompute(depth, value) {
      if (depth === 0) {
          return value;
      }
      let accumulated = 0;
      for (let i = 0; i < 3; i = i + 1) {
          {
              let partial = deepCompute(depth - 1, value + i);
              accumulated = accumulated + partial;
          }
      }
      return accumulated;
  }
  console.log("Deep compute:", deepCompute(4, 1));

  console.log("All nested tests passed!");
}

{
  // MVP test: nested loops - multiplication table (JS equivalent of nested_loops.tish)
  let i = 0;
  let j = 0;
  for (let row = 1; row <= 3; row = row + 1) {
    for (let col = 1; col <= 3; col = col + 1) {
      console.log(row, "x", col, "=", row * col);
    }
  }
  console.log("i after loops:", i);
  console.log("j after loops:", j);
}

{
  // Performance tests for new features

  let iterations = 10000;
  let start = 0;
  let end = 0;

  console.log("=== Performance tests for new features ===");
  console.log("Iterations: " + iterations);

  // array.sort() performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [5, 2, 8, 1, 9, 3, 7, 4, 6];
      arr.sort((a, b) => a - b);
  }
  end = Date.now();
  console.log("array.sort() with comparator: " + (end - start) + "ms");

  // array.splice() performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr = [1, 2, 3, 4, 5];
      arr.splice(2, 1, 'a', 'b');
  }
  end = Date.now();
  console.log("array.splice(): " + (end - start) + "ms");

  // Object.assign() performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let target = { a: 1 };
      let source = { b: 2, c: 3 };
      Object.assign(target, source);
  }
  end = Date.now();
  console.log("Object.assign(): " + (end - start) + "ms");

  // Object.fromEntries() performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let entries = [["a", 1], ["b", 2], ["c", 3]];
      Object.fromEntries(entries);
  }
  end = Date.now();
  console.log("Object.fromEntries(): " + (end - start) + "ms");

  // Array destructuring performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let [a, b, c] = [1, 2, 3];
  }
  end = Date.now();
  console.log("Array destructuring: " + (end - start) + "ms");

  // Object destructuring performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let { x, y, z } = { x: 1, y: 2, z: 3 };
  }
  end = Date.now();
  console.log("Object destructuring: " + (end - start) + "ms");

  // Array spread performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let arr1 = [1, 2, 3];
      let arr2 = [...arr1, 4, 5];
  }
  end = Date.now();
  console.log("Array spread: " + (end - start) + "ms");

  // Object spread performance
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let obj1 = { a: 1, b: 2 };
      let obj2 = { ...obj1, c: 3 };
  }
  end = Date.now();
  console.log("Object spread: " + (end - start) + "ms");

  // Function call spread performance
  let sum3 = (a, b, c) => a + b + c;
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      let args = [1, 2, 3];
      sum3(...args);
  }
  end = Date.now();
  console.log("Function call spread: " + (end - start) + "ms");

  // Default parameters performance
  let greet = (name = "World") => "Hello, " + name;
  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      greet();
  }
  end = Date.now();
  console.log("Default parameters (using default): " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < iterations; i++) {
      greet("Alice");
  }
  end = Date.now();
  console.log("Default parameters (with arg): " + (end - start) + "ms");

  console.log("=== Performance tests complete ===");
}

{
  // Test Object.keys, Object.values, Object.entries

  let obj = { name: "Alice", age: 30, city: "NYC" };

  // Object.keys
  let keys = Object.keys(obj);
  console.log("keys count:", keys.length);

  // Object.values
  let vals = Object.values(obj);
  console.log("values count:", vals.length);

  // Object.entries
  let entries = Object.entries(obj);
  console.log("entries count:", entries.length);

  // Iterate with forEach over entries (sort for deterministic order)
  let sortedEntries = Object.entries(obj).sort((a, b) => a[0].localeCompare(b[0]));
  function printEntry(entry) {
      console.log("  key:", entry[0], "val:", entry[1]);
  }
  console.log("entries:");
  sortedEntries.forEach(printEntry);

  // Use with map
  function getKey(entry) { return entry[0]; }
  let keyNames = Object.entries(obj).map(getKey).sort();
  console.log("mapped keys:", keyNames.join(","));

  // Empty object
  let empty = {};
  console.log("empty keys:", Object.keys(empty).length);
  console.log("empty values:", Object.values(empty).length);
  console.log("empty entries:", Object.entries(empty).length);

  // Nested object
  let nested = {
      a: 1,
      b: { x: 10, y: 20 },
      c: [1, 2, 3]
  };
  console.log("nested keys:", Object.keys(nested).length);
}

{
  // Object manipulation stress tests
  // Tests object operations at scale to identify bottlenecks

  let start = 0;
  let end = 0;

  console.log("=== Object Stress Tests ===");
  console.log("");

  // === OBJECT CREATION ===
  console.log("--- Object Creation ---");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let obj = {};
  }
  end = Date.now();
  console.log("Empty object creation x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let obj = { a: 1, b: 2, c: 3 };
  }
  end = Date.now();
  console.log("3-prop literal x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let obj = { a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10 };
  }
  end = Date.now();
  console.log("10-prop literal x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let x = i;
      let obj = { x: x, y: x + 1, z: x * 2 };
  }
  end = Date.now();
  console.log("Computed props x5000: " + (end - start) + "ms");

  // === PROPERTY ACCESS ===
  console.log("");
  console.log("--- Property Access ---");

  let smallObj = { x: 1, y: 2, z: 3 };
  let largeObj = { a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10,
                    k: 11, l: 12, m: 13, n: 14, o: 15, p: 16, q: 17, r: 18, s: 19, t: 20 };

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = smallObj.x;
  }
  end = Date.now();
  console.log("Dot access (first prop) x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = smallObj.z;
  }
  end = Date.now();
  console.log("Dot access (last of 3) x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = largeObj.t;
  }
  end = Date.now();
  console.log("Dot access (last of 20) x10000: " + (end - start) + "ms");

  let key = "x";
  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = smallObj[key];
  }
  end = Date.now();
  console.log("Bracket access x10000: " + (end - start) + "ms");

  let keys = ["a", "j", "t"];
  start = Date.now();
  for (let i = 0; i < 3000; i++) {
      for (let k of keys) {
          let v = largeObj[k];
      }
  }
  end = Date.now();
  console.log("Dynamic key access (3 keys x3000): " + (end - start) + "ms");

  // === PROPERTY WRITE ===
  console.log("");
  console.log("--- Property Write ---");

  let writeObj = { x: 0, y: 0, z: 0 };
  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      writeObj.x = i;
  }
  end = Date.now();
  console.log("Dot write x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      writeObj[key] = i;
  }
  end = Date.now();
  console.log("Bracket write x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let obj = {};
      obj.a = 1;
      obj.b = 2;
      obj.c = 3;
  }
  end = Date.now();
  console.log("Dynamic prop add x5000: " + (end - start) + "ms");

  // === DEEP NESTED ACCESS ===
  console.log("");
  console.log("--- Deep Nested Access ---");

  let deep3 = { a: { b: { c: 42 } } };
  let deep5 = { a: { b: { c: { d: { e: 42 } } } } };
  let deep7 = { a: { b: { c: { d: { e: { f: { g: 42 } } } } } } };

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = deep3.a.b.c;
  }
  end = Date.now();
  console.log("3-level deep access x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = deep5.a.b.c.d.e;
  }
  end = Date.now();
  console.log("5-level deep access x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = deep7.a.b.c.d.e.f.g;
  }
  end = Date.now();
  console.log("7-level deep access x10000: " + (end - start) + "ms");

  // === OPTIONAL CHAINING ===
  console.log("");
  console.log("--- Optional Chaining ---");

  let maybeObj = { a: { b: { c: 42 } } };
  let nullObj = { a: null };

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = maybeObj?.a?.b?.c;
  }
  end = Date.now();
  console.log("Optional chain (all exist) x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let v = nullObj?.a?.b?.c;
  }
  end = Date.now();
  console.log("Optional chain (short-circuit) x10000: " + (end - start) + "ms");

  // === OBJECT SPREAD ===
  console.log("");
  console.log("--- Object Spread ---");

  let base3 = { a: 1, b: 2, c: 3 };
  let base10 = { a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10 };

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let copy = { ...base3 };
  }
  end = Date.now();
  console.log("Spread copy (3 props) x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let copy = { ...base10 };
  }
  end = Date.now();
  console.log("Spread copy (10 props) x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let merged = { ...base3, d: 4, e: 5 };
  }
  end = Date.now();
  console.log("Spread + extend x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 3000; i++) {
      let merged = { ...base3, ...base10 };
  }
  end = Date.now();
  console.log("Merge two objects x3000: " + (end - start) + "ms");

  // === OBJECT.ASSIGN ===
  console.log("");
  console.log("--- Object.assign ---");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let target = {};
      Object.assign(target, base3);
  }
  end = Date.now();
  console.log("assign to empty x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let target = { x: 0 };
      Object.assign(target, base3, base10);
  }
  end = Date.now();
  console.log("assign multiple sources x5000: " + (end - start) + "ms");

  // === OBJECT.KEYS/VALUES/ENTRIES ===
  console.log("");
  console.log("--- Object.keys/values/entries ---");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      Object.keys(base10);
  }
  end = Date.now();
  console.log("Object.keys (10 props) x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      Object.values(base10);
  }
  end = Date.now();
  console.log("Object.values (10 props) x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      Object.entries(base10);
  }
  end = Date.now();
  console.log("Object.entries (10 props) x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let entries = [["a", 1], ["b", 2], ["c", 3]];
      Object.fromEntries(entries);
  }
  end = Date.now();
  console.log("Object.fromEntries x5000: " + (end - start) + "ms");

  // === 'IN' OPERATOR ===
  console.log("");
  console.log("--- 'in' Operator ---");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let has = "a" in base10;
  }
  end = Date.now();
  console.log("'in' existing key x10000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 10000; i++) {
      let has = "z" in base10;
  }
  end = Date.now();
  console.log("'in' missing key x10000: " + (end - start) + "ms");

  // === DESTRUCTURING ===
  console.log("");
  console.log("--- Destructuring ---");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let { a, b, c } = base3;
  }
  end = Date.now();
  console.log("Destructure 3 props x5000: " + (end - start) + "ms");

  start = Date.now();
  for (let i = 0; i < 5000; i++) {
      let { a, b, c, d, e, f, g, h, i: ii, j } = base10;
  }
  end = Date.now();
  console.log("Destructure 10 props x5000: " + (end - start) + "ms");

  // Match Tish test: no rest support
  start = Date.now();
  for (let i = 0; i < 3000; i++) {
      let { a, b, c, d, e } = base10;
  }
  end = Date.now();
  console.log("Destructure 5 props x3000: " + (end - start) + "ms");

  // === OBJECT ITERATION ===
  console.log("");
  console.log("--- Object Iteration ---");

  start = Date.now();
  for (let i = 0; i < 2000; i++) {
      for (let k of Object.keys(base10)) {
          let v = base10[k];
      }
  }
  end = Date.now();
  console.log("for-of Object.keys x2000: " + (end - start) + "ms");

  // Match Tish test: no destructuring in for-of
  start = Date.now();
  for (let i = 0; i < 2000; i++) {
      for (let entry of Object.entries(base10)) {
          let x = entry[0] + entry[1];
      }
  }
  end = Date.now();
  console.log("for-of Object.entries x2000: " + (end - start) + "ms");

  // === FACTORY PATTERNS ===
  console.log("");
  console.log("--- Factory Patterns ---");

  function createUser(id, name) {
      return { id: id, name: name, active: true, createdAt: Date.now() };
  }
  start = Date.now();
  for (let i = 0; i < 3000; i++) {
      createUser(i, "user" + i);
  }
  end = Date.now();
  console.log("Factory function x3000: " + (end - start) + "ms");

  // Match Tish test: no method syntax
  function createWithValue(val) {
      return { value: val, doubled: val * 2 };
  }
  start = Date.now();
  for (let i = 0; i < 2000; i++) {
      let obj = createWithValue(i);
      let v = obj.value;
      let d = obj.doubled;
  }
  end = Date.now();
  console.log("Factory + access x2000: " + (end - start) + "ms");

  console.log("");
  console.log("=== Object Stress Tests Complete ===");
}

{
  // Comprehensive test: plain objects and property access (JS equivalent)
  // Tests: literals, dot access, bracket access, nested objects, objects with functions
  // NOTE: JS returns undefined where Tish returns null (semantic difference)

  // Basic object creation
  const pt = { x: 10, y: 20 };
  console.log(pt.x);
  console.log(pt.y);

  // Bracket access with string literal
  console.log(pt["x"]);

  // Dynamic property access
  const propName = "y";
  console.log(pt[propName]);

  // Multiple properties
  const rec = { a: 1, b: 2, c: 3 };
  console.log(rec.a, rec.b, rec.c);

  // Nested objects
  const nested = {
    outer: {
      inner: {
        value: 42
      }
    }
  };
  console.log(nested.outer.inner.value);
  console.log(nested["outer"]["inner"]["value"]);

  // Mixed dot and bracket access
  console.log(nested.outer["inner"].value);

  // Objects with different value types
  const mixed = {
    num: 123,
    str: "hello",
    bool: true,
    nil: null,
    arr: [1, 2, 3],
    obj: { nested: true }
  };
  console.log(mixed.num);
  console.log(mixed.str);
  console.log(mixed.bool);
  console.log(mixed.nil);
  console.log(mixed.arr[1]);
  console.log(mixed.obj.nested);

  // Dynamic property access with bracket notation
  const dynamicKey = "x";
  console.log(pt[dynamicKey]);

  // Objects as function parameters
  const getX = (obj) => obj.x;
  const getY = (obj) => obj.y;
  console.log(getX(pt));
  console.log(getY(pt));

  // Functions returning objects
  function makePoint(x, y) {
    return { x: x, y: y };
  }
  const p = makePoint(100, 200);
  console.log(p.x, p.y);

  // Object in conditional
  const config = { enabled: true, count: 5 };
  if (config.enabled)
    console.log("enabled with count:", config.count);

  // Object in loop iteration (accessing properties)
  const items = [
    { name: "a", val: 1 },
    { name: "b", val: 2 },
    { name: "c", val: 3 }
  ];
  for (const item of items)
    console.log(item.name, item.val);

  // typeof object
  console.log(typeof {});
  console.log(typeof { x: 1 });
  console.log(typeof nested);

  // Object equality (reference comparison)
  const obj1 = { x: 1 };
  const obj2 = { x: 1 };
  const obj3 = obj1;
  console.log(obj1 === obj2);
  console.log(obj1 === obj3);

  // 'in' operator
  const testIn = { a: 1, b: 2 };
  console.log("a" in testIn);
  console.log("c" in testIn);

  // Optional chaining with objects
  const maybeNull = null;
  console.log(maybeNull?.x);
  const hasX = { x: 99 };
  console.log(hasX?.x);

  // Deep optional chaining
  const deep = { a: { b: { c: 1 } } };
  const shallow = { a: null };
  console.log(deep?.a?.b?.c);
  console.log(shallow?.a?.b?.c);

  // Nullish coalescing with object properties
  const withNull = { val: null };
  const withValue = { val: 42 };
  console.log(withNull.val ?? "default");
  console.log(withValue.val ?? "default");
}

{
  // Performance test: heavy object workload (JS equivalent)
  // Stresses object creation, property access, and iteration

  // Create many objects in a loop
  const objects = [];
  for (let i = 0; i < 100; i = i + 1) {
    // Note: We can't do objects.push(), so we create arrays with spread would be needed
    // For now, test object creation and access patterns
  }

  // Deep property access chains
  const data = {
    users: {
      admin: {
        profile: {
          name: "Admin",
          level: 10
        }
      },
      guest: {
        profile: {
          name: "Guest",
          level: 1
        }
      }
    }
  };

  // Repeated deep access (simulates hot path)
  let sum = 0;
  for (let i = 0; i < 1000; i = i + 1) {
    sum = sum + data.users.admin.profile.level;
    sum = sum + data.users.guest.profile.level;
  }
  console.log("sum:", sum);

  // Object property lookup with dynamic keys
  const keys = ["a", "b", "c", "d", "e"];
  const lookup = { a: 1, b: 2, c: 3, d: 4, e: 5 };
  let total = 0;
  for (const k of keys) {
    total = total + lookup[k];
  }
  console.log("total:", total);

  // Nested object traversal
  const tree = {
    val: 1,
    left: {
      val: 2,
      left: { val: 4, left: null, right: null },
      right: { val: 5, left: null, right: null }
    },
    right: {
      val: 3,
      left: { val: 6, left: null, right: null },
      right: { val: 7, left: null, right: null }
    }
  };

  // Simple tree value access
  console.log("root:", tree.val);
  console.log("left:", tree.left.val);
  console.log("right:", tree.right.val);
  console.log("left-left:", tree.left.left.val);
  console.log("left-right:", tree.left.right.val);
  console.log("right-left:", tree.right.left.val);
  console.log("right-right:", tree.right.right.val);

  // Many small object creations
  function makeRecord(id, name, active) {
    return { id: id, name: name, active: active };
  }

  const records = [
    makeRecord(1, "Alice", true),
    makeRecord(2, "Bob", false),
    makeRecord(3, "Charlie", true),
    makeRecord(4, "Diana", true),
    makeRecord(5, "Eve", false)
  ];

  let activeCount = 0;
  for (const r of records) {
    if (r.active)
      activeCount = activeCount + 1;
  }
  console.log("active:", activeCount);

  // Optional chaining performance
  const maybeData = {
    level1: {
      level2: {
        level3: {
          value: 42
        }
      }
    }
  };

  let chainSum = 0;
  for (let i = 0; i < 500; i = i + 1) {
    chainSum = chainSum + (maybeData?.level1?.level2?.level3?.value ?? 0);
  }
  console.log("chainSum:", chainSum);

  // 'in' operator performance
  const checkObj = { a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10 };
  let inCount = 0;
  const testKeys = ["a", "b", "z", "c", "d", "x", "e", "f", "y", "g"];
  for (let i = 0; i < 100; i = i + 1) {
    for (const k of testKeys) {
      if (k in checkObj)
        inCount = inCount + 1;
    }
  }
  console.log("inCount:", inCount);
}

{
  // MVP test: optional braces - indentation logic (JS equivalent of optional_braces.tish)
  const n = 3;
  if (n > 0) {
    console.log("positive");
    const x = 1;
    if (x === 1)
      console.log("nested if, no braces");
  }
  console.log("done");
}

{
  // MVP test: optional braces - braced version (JS equivalent of optional_braces_braced.tish)
  const n = 3;
  if (n > 0) {
    console.log("positive");
    const x = 1;
    if (x === 1) {
      console.log("nested if, with braces");
    }
  }
  console.log("done");
}

{
  // MVP test: optional chaining ?. and nullish coalescing ?? (JS equivalent of optional_chaining.tish)
  let x = null;
  console.log(x ?? "default");
  let y = 0;
  console.log(y ?? 99);
  let z = "hello";
  console.log(z ?? "default");
  const obj = { a: 1, b: 2 };
  console.log(obj?.a);
  console.log(obj?.c ?? "missing");
}

{
  // MVP test: rest parameters
  function sum(...args) {
    let total = 0;
    for (const x of args)
      total = total + x;
    return total;
  }
  console.log(sum(1, 2, 3));
  console.log(sum(10, 20));

  function greet(first, ...rest) {
    return first + ":" + rest.length;
  }
  console.log(greet("a", "b", "c"));
}

{
  // Reference JS for the same prints as scopes.tish (Tish is simpler: no var hoisting, no let/const TDZ).
  let x = 1;
  console.log("outer x:", x);
  {
    let x = 2;
    console.log("inner x:", x);
  }
  console.log("outer x after block:", x);

  let y = 10;
  {
    let y = 20;
    console.log("inner y:", y);
  }
  console.log("outer y:", y);

  let a = 100;
  {
    let a = 200;
    console.log("block1 a:", a);
    {
      let a = 300;
      console.log("block2 a:", a);
    }
    console.log("block1 a after inner:", a);
  }
  console.log("outer a:", a);

  let z = 1;
  function g() {
    let z = 2;
    console.log("fn z:", z);
  }
  g();
  console.log("script z:", z);

  let b = 1;
  if (true) {
    let b = 2;
    console.log("if block b:", b);
  }
  console.log("outer b after if:", b);
}

{
  // MVP test: space indentation (JS equivalent of space_indent.tish)
  const x = 1;
  if (x === 1) {
    console.log("space-indented");
    const y = 2;
    if (y === 2)
      console.log("nested with spaces");
  }
  console.log("done");
}

{
  // MVP test: strict equality - no coercion (JS equivalent of strict_equality.tish)
  console.log(1 === 1);
  console.log(1 === 2);
  console.log(1 === "1");
  console.log("1" === "1");
  console.log(1 + 2);
  console.log(1 !== "1");
  console.log(null === null);
}

{
  // String methods tests

  let str = "Hello, World!"

  // indexOf
  console.log(str.indexOf("World"))
  console.log(str.indexOf("xyz"))
  console.log(str.indexOf("o", 5))
  console.log(str.indexOf("H", 1))

  // includes
  console.log(str.includes("World"))
  console.log(str.includes("xyz"))
  console.log(str.includes("o", 5))
  console.log(str.includes("h", -1))

  // slice
  console.log(str.slice(0, 5))
  console.log(str.slice(7))
  console.log(str.slice(-6))
  console.log(str.slice(0, -7))

  // substring
  console.log(str.substring(0, 5))
  console.log(str.substring(7, 12))

  // split
  let csv = "a,b,c,d"
  let parts = csv.split(",")
  console.log(parts.length)
  console.log(parts[0])
  console.log(parts[2])

  // trim
  let padded = "  hello  "
  console.log(padded.trim())

  // toUpperCase / toLowerCase
  let mixed = "Hello"
  console.log(mixed.toUpperCase())
  console.log(mixed.toLowerCase())

  // startsWith / endsWith
  let path = "/api/users"
  console.log(path.startsWith("/api"))
  console.log(path.startsWith("/home"))
  console.log(path.endsWith("users"))
  console.log(path.endsWith("admin"))

  // replace / replaceAll
  let text = "foo bar foo"
  console.log(text.replace("foo", "baz"))
  console.log(text.replaceAll("foo", "baz"))

  // charAt
  console.log("abc".charAt(0))
  console.log("abc".charAt(1))
  console.log("abc".charAt(99))

  // charCodeAt
  console.log("ABC".charCodeAt(0))
  console.log("ABC".charCodeAt(1))

  // repeat
  console.log("ab".repeat(3))
  console.log("x".repeat(0))

  // padStart / padEnd
  console.log("5".padStart(3, "0"))
  console.log("hi".padEnd(5, "!"))
  console.log("hello".padStart(3))

  // lastIndexOf
  let hay = "abcabc"
  console.log(hay.lastIndexOf("a"))
  console.log(hay.lastIndexOf("a", 2))
  console.log(hay.lastIndexOf("x"))
  console.log(hay.lastIndexOf(""))
  console.log(hay.lastIndexOf("", 3))
  // BMP only so Node (UTF-16 indices) matches Tish (scalar indices)
  let uni = "éaé"
  console.log(uni.lastIndexOf("a"))
  console.log(uni.lastIndexOf("é"))
  console.log("aba".lastIndexOf("a", null))

  // length property
  console.log("test".length)
  console.log("".length)
}

{
  // String methods performance test - intensive operations

  let iterations = 500

  // Test indexOf/includes
  let text = "The quick brown fox jumps over the lazy dog"
  let found = 0
  let i = 0
  while (i < iterations) {
      if (text.includes("fox")) {
          found = found + 1
      }
      if (text.indexOf("lazy") > -1) {
          found = found + 1
      }
      if (text.lastIndexOf("dog") > -1) {
          found = found + 1
      }
      i = i + 1
  }
  console.log(found)

  // Test split/join roundtrip
  let csv = "a,b,c,d,e,f,g"
  let result = ""
  i = 0
  while (i < iterations) {
      let parts = csv.split(",")
      result = parts.join("-")
      i = i + 1
  }
  console.log(result)

  // Test slice/substring
  let str = "Hello World!"
  let sliced = ""
  i = 0
  while (i < iterations) {
      sliced = str.slice(0, 5)
      sliced = str.substring(6, 11)
      i = i + 1
  }
  console.log(sliced)

  // Test replace/replaceAll
  let template = "{{name}} is {{age}} years old"
  let replaced = ""
  i = 0
  while (i < iterations) {
      replaced = template.replace("{{name}}", "John")
      replaced = replaced.replace("{{age}}", "25")
      i = i + 1
  }
  console.log(replaced)

  // Test toUpperCase/toLowerCase
  let mixed = "Hello World"
  let upper = ""
  let lower = ""
  i = 0
  while (i < iterations) {
      upper = mixed.toUpperCase()
      lower = mixed.toLowerCase()
      i = i + 1
  }
  console.log(upper)
  console.log(lower)

  // Test trim
  let padded = "   trimmed   "
  let trimmed = ""
  i = 0
  while (i < iterations) {
      trimmed = padded.trim()
      i = i + 1
  }
  console.log(trimmed)

  // Test startsWith/endsWith
  let path = "/api/users/123"
  let count = 0
  i = 0
  while (i < iterations) {
      if (path.startsWith("/api")) {
          count = count + 1
      }
      if (path.endsWith("123")) {
          count = count + 1
      }
      i = i + 1
  }
  console.log(count)

  // Test repeat/pad
  let base = "x"
  let repeated = ""
  i = 0
  while (i < 200) {
      repeated = base.repeat(10)
      let padded2 = "5".padStart(5, "0")
      i = i + 1
  }
  console.log(repeated.length)

  // Test charAt/charCodeAt
  let alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  let sum = 0
  i = 0
  while (i < iterations) {
      let code = alphabet.charCodeAt(0)
      sum = sum + code
      i = i + 1
  }
  console.log(sum)
}

{
  // MVP test: switch statement (JS equivalent of switch.tish)
  let x = 2;
  switch (x) {
    case 1:
      console.log("one");
      break;
    case 2:
      console.log("two");
      break;
    case 3:
      console.log("three");
      break;
  }
  console.log("done");
  let y = 99;
  switch (y) {
    case 1:
      console.log("one");
      break;
    default:
      console.log("default");
  }
  console.log("end");
}

{
  // MVP test: tab indentation (JS equivalent of tab_indent.tish)
  const x = 1;
  if (x === 1) {
  	console.log("tab-indented");
  	const y = 2;
  	if (y === 2)
  		console.log("nested with tabs");
  }
  console.log("done");
}

{
  // Test template literal interpolation

  // Basic interpolation
  let name = "World";
  console.log(`Hello, ${name}!`);

  // Arithmetic in interpolation
  let a = 5;
  let b = 10;
  console.log(`${a} + ${b} = ${a + b}`);

  // Array method in interpolation
  let nums = [1, 2, 3];
  console.log(`Array: ${nums.join(", ")}`);

  // Multiple interpolations
  let first = "John";
  let last = "Doe";
  let age = 30;
  console.log(`Name: ${first} ${last}, Age: ${age}`);

  // Boolean expression
  console.log(`Is adult: ${age >= 18}`);

  // Empty string
  let empty = "";
  console.log(`Empty: [${empty}]`);

  // Simple template (no interpolation)
  console.log(`Plain template`);

  // Object property in interpolation
  let person = { name: "Alice", age: 25 };
  console.log(`Person: ${person.name}, ${person.age}`);

  // Function call in interpolation
  function double(x) { return x * 2; }
  console.log(`Double 5: ${double(5)}`);

  // Ternary in interpolation
  let x = 5;
  console.log(`Value: ${x > 3 ? "big" : "small"}`);

  // Multiline template
  let multi = `Line 1
  Line 2
  Line 3`;
  console.log(multi);

  // Escaping
  console.log(`Dollar: \$, Backtick: \`, Backslash: \\`);

  // Nested object access
  let data = { inner: { value: 42 } };
  console.log(`Nested: ${data.inner.value}`);

  // Chained method calls
  let words = ["hello", "world"];
  console.log(`Joined: ${words.join(" ").toUpperCase()}`);
}

{
  // MVP test: try/catch and throw (JS equivalent of try_catch.tish)
  try {
    console.log("in try");
    throw "oops";
    console.log("never");
  } catch (e) {
    console.log("caught:", e);
  }
  console.log("done");
  try {
    throw 42;
  } catch (x) {
    console.log("got", x);
  }
}

{
  // MVP test: typeof operator (JS equivalent of typeof.tish)
  console.log(typeof 1);
  console.log(typeof "hi");
  console.log(typeof true);
  console.log(typeof null);
  console.log(typeof [1, 2]);
  console.log(typeof { a: 1 });
  function f() { return 1; }
  console.log(typeof f);
}

{
  // Type annotation tests - JS equivalent
  // Note: JS doesn't have native type annotations, but TypeScript does

  // Simple type annotations (JS uses runtime values)
  let x = 42;
  let name = "hello";
  let flag = true;
  let empty = null;

  // Array types
  let nums = [1, 2, 3];
  let strs = ["a", "b", "c"];

  // Function with typed parameters and return type
  function add(a, b) {
      return a + b;
  }

  // Function returning void
  function greet(msg) {
      console.log(msg);
  }

  // Verify values work
  console.log(add(x, 10));
  greet("Welcome!");
  console.log(name);
  console.log(nums[1]);

  // Const with type
  const PI = 3.14159;
  console.log(PI);

  // Object type annotation
  let person = { name: "Alice", age: 30 };
  console.log(person.name);

  // Union types
  let value = 42;
  console.log(value);

  // Function with rest params typed
  function sum(...args) {
      let total = 0;
      for (const n of args) {
          total = total + n;
      }
      return total;
  }
  console.log(sum(1, 2, 3, 4, 5));
}

{
  // MVP perf: decodeURI and encodeURI
  console.log(encodeURI("hello world"));
  console.log(decodeURI("hello%20world"));
  console.log(encodeURI("a=b&c=d"));
  console.log(decodeURI("a%3Db%26c%3Dd"));
}

{
  // MVP test: void operator (evaluates operand, returns undefined)
  const x = void (1 + 2);
  console.log(typeof x);
  console.log(x === undefined);
  const dummy = void console.log("side effect");
}

{
  // Promise tests - JS equivalent for validation
  // Run: node tests/modules/promise.js  (Node 18+ with top-level await, or use --input-type=module)
  // Or: node -e "$(cat tests/modules/promise.js | sed 's/^/  /')" with async IIFE

  (async () => {
  // Promise(executor) - sync resolve
  let p1 = new Promise((resolve, reject) => { resolve(42) })
  let v1 = await p1
  console.log("Promise sync resolve:", v1)

  // Promise.resolve
  let p2 = Promise.resolve(100)
  let v2 = await p2
  console.log("Promise.resolve:", v2)

  // Promise.reject
  let ok = false
  try {
    await Promise.reject("err")
  } catch (e) {
    ok = (e === "err")
  }
  console.log("Promise.reject caught:", ok)

  // .then chain
  let p3 = Promise.resolve(1).then(x => x + 1).then(x => x * 2)
  let v3 = await p3
  console.log(".then chain:", v3)

  // .catch
  let p4 = Promise.reject("fail").catch(e => "handled: " + e)
  let v4 = await p4
  console.log(".catch:", v4)

  // Promise.all
  let pa = Promise.all([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)])
  let va = await pa
  console.log("Promise.all:", va[0], va[1], va[2])

  // Promise.race
  let pr = Promise.race([Promise.resolve("fast"), Promise.resolve("slow")])
  let vr = await pr
  console.log("Promise.race:", vr)

  console.log("Promise tests completed")
  })()
}

{
  // setTimeout tests - JS equivalent for validation
  // Run: node tests/modules/settimeout.js

  console.log("Before setTimeout")
  setTimeout(() => { console.log("After 0ms (immediate)") }, 0)
  console.log("After first setTimeout")

  let id = setTimeout(() => { console.log("Delay completed") }, 1)
  console.log("setTimeout returned id:", id)

  clearTimeout(id)
  console.log("setTimeout tests completed")
}
