//! LLVM backend for Tish.
//!
//! Compiles Tish bytecode to native binary using clang (LLVM toolchain).
//! Emits a C file with embedded bytecode, compiles with clang to object code,
//! then links with tish_cranelift_runtime.

use std::fs;
use std::path::Path;
use std::process::Command;

use tish_bytecode::{serialize, Chunk};
use tish_compile::{detect_cycles, merge_modules, resolve_project};

/// Compile a Tish program to a native binary via clang/LLVM.
pub fn compile_to_native(
    entry_path: &Path,
    project_root: Option<&Path>,
    output_path: &Path,
) -> Result<(), LlvmError> {
    let modules = resolve_project(entry_path, project_root)
        .map_err(|e| LlvmError { message: e.to_string() })?;
    detect_cycles(&modules).map_err(|e| LlvmError { message: e.to_string() })?;
    let program = merge_modules(modules).map_err(|e| LlvmError { message: e.to_string() })?;
    let chunk = tish_bytecode::compile(&program).map_err(|e| LlvmError {
        message: e.to_string(),
    })?;

    compile_chunk_to_native(&chunk, output_path)
}

/// Compile a bytecode chunk to a native binary.
pub fn compile_chunk_to_native(chunk: &Chunk, output_path: &Path) -> Result<(), LlvmError> {
    let chunk_bytes = serialize(chunk);
    let out_name = output_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("tish_out");
    let build_dir = tish_build_utils::create_build_dir("tish_llvm_build", out_name)
        .map_err(|e| LlvmError { message: e })?;

    // Generate C source with embedded bytecode (data only; main comes from Rust link step)
    let bytes_str: Vec<String> = chunk_bytes.iter().map(|b| b.to_string()).collect();
    let chunk_c = format!(
        r#"/* Generated by tish_llvm - do not edit */
#include <stddef.h>
#include <stdint.h>

const uint8_t tish_chunk_data[] = {{ {} }};
const uint64_t tish_chunk_len = sizeof(tish_chunk_data);
"#,
        bytes_str.join(",")
    );

    let chunk_c_path = build_dir.join("chunk.c");
    fs::write(&chunk_c_path, chunk_c).map_err(|e| LlvmError {
        message: format!("Cannot write chunk.c: {}", e),
    })?;

    // Compile C to object file using clang (LLVM)
    let object_path = build_dir.join("chunk.o");
    let clang = std::env::var("CLANG").unwrap_or_else(|_| "clang".to_string());
    let status = Command::new(&clang)
        .args(["-c", "-o"])
        .arg(&object_path)
        .arg(&chunk_c_path)
        .status()
        .map_err(|e| LlvmError {
            message: format!("Failed to run clang: {}. Install clang (LLVM) or set CLANG env var.", e),
        })?;

    if !status.success() {
        return Err(LlvmError {
            message: "clang compilation failed. Ensure clang (LLVM) is installed.".to_string(),
        });
    }

    // Link using the same infrastructure as Cranelift (links .o with tish_cranelift_runtime)
    let object_path_canonical = object_path.canonicalize().map_err(|e| LlvmError {
        message: format!("Cannot canonicalize object path: {}", e),
    })?;
    tish_cranelift::link_to_binary(&object_path_canonical, output_path).map_err(|e| LlvmError {
        message: e.message,
    })?;

    Ok(())
}

/// Error from LLVM compilation.
#[derive(Debug)]
pub struct LlvmError {
    pub message: String,
}

impl std::fmt::Display for LlvmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for LlvmError {}
