// #247 cross-backend built-in divergences (Math round/min/max/hypot, parseInt radix, includes(NaN),
// toFixed, -0 ToString) — fixed to match the JS target. interp/vm/native/cranelift/node must all
// agree. Valid in tish and node. (instanceof/at/findLast tracked separately.)
console.log("round-neg", Math.round(-2.5))
console.log("round-pos", Math.round(2.5))
console.log("round-half", Math.round(0.5))
console.log("min-empty", Math.min())
console.log("max-empty", Math.max())
console.log("min-nan", Math.min(1, 0 / 0))
console.log("min-vals", Math.min(3, 1, 2))
console.log("max-vals", Math.max(3, 1, 2))
console.log("hypot", Math.hypot(3, 4))
console.log("hypot3", Math.hypot(3, 4, 12))
console.log("hypot-empty", Math.hypot())
console.log("hypot-nan", Math.hypot(0 / 0, 4))
console.log("hypot-inf", Math.hypot(1 / 0, 0 / 0))
console.log("atan2", Math.atan2(1, 1))
// Math.imul: exact 32-bit multiply (ToInt32 both operands, wrapping) — NOT a saturating cast. The
// large-arg cases (args >= 2^31) are the ones the old `as i32` cast got wrong; all backends now agree.
console.log("imul-small", Math.imul(3, 4))
console.log("imul-u32", Math.imul(0xffffffff, 5))
console.log("imul-over", Math.imul(3000000000, 1))
console.log("imul-neg", Math.imul(-5, -5))
// Math.sign preserves the sign of -0 (1/-0 = -Infinity distinguishes -0 from +0).
console.log("sign-neg0", 1 / Math.sign(-0))
console.log("sign-pos0", 1 / Math.sign(0))
console.log("sign-neg", Math.sign(-5))
// padStart/padEnd with an explicit empty fill add NO padding; an absent fill defaults to a space.
console.log("pad-empty", "x".padStart(3, ""))
console.log("pad-space", "x".padStart(3))
console.log("padend-empty", "x".padEnd(3, ""))
// [].reduce with no initial value throws TypeError; an explicit init (incl. null) is returned as-is.
let redThrew = "no"
try { [].reduce((a, b) => a + b) } catch (e) { redThrew = e.name }
console.log("reduce-empty-throw", redThrew)
console.log("reduce-empty-init", [].reduce((a, b) => a + b, 42))
console.log("reduce-empty-null", [].reduce((a, b) => a + b, null))
// Out-of-range / negative string index reads falsy (null in tish, undefined in node) — no throw.
console.log("str-oob", "abc"[10] || "none")
console.log("str-neg", "abc"[-1] || "none")
// JSON.stringify escapes control chars (valid JSON), not raw bytes.
console.log("json-nul", JSON.stringify(String.fromCharCode(0)))
console.log("json-bs", JSON.stringify(String.fromCharCode(8)))
// 2nd-arg support: Array.indexOf fromIndex; String.startsWith/endsWith position.
console.log("idxof-from", [1, 2, 1, 3].indexOf(1, 1))
console.log("idxof-neg", [1, 2, 3, 2, 1].indexOf(2, -2))
console.log("startsw-pos", "abc".startsWith("bc", 1))
console.log("endsw-pos", "abc".endsWith("ab", 2))
// Global isNaN/isFinite coerce their arg via ToNumber (like Number()).
console.log("isnan-str", isNaN("3"), isNaN("x"), isNaN(""))
console.log("isfinite-str", isFinite("3"), isFinite("x"), isFinite(""))
console.log("trimstart", "[" + "  x  ".trimStart() + "]")
console.log("trimend", "[" + "  x  ".trimEnd() + "]")
console.log("num-isint", Number.isInteger(5), Number.isInteger(5.5), Number.isInteger("5"))
console.log("num-safe", Number.isSafeInteger(9007199254740991), Number.isSafeInteger(9007199254740993))
console.log("num-nan", Number.isNaN(0/0), Number.isNaN("x"), Number.isFinite(1/0))
console.log("num-max", Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER)
console.log("objis", Object.is(NaN, NaN), Object.is(0, -0), Object.is(2, 2))
console.log("arrof", Array.of(7).length, Array.of(1, 2, 3).join(","))
console.log("lastidx", [1,2,1,3,1].lastIndexOf(1), [1,2,3].lastIndexOf(5), [1,2,1].lastIndexOf(1,-2))
console.log("copywithin", [1,2,3,4,5].copyWithin(0,3).join(","))
console.log("includes-nan", [1, 0 / 0].includes(0 / 0))
console.log("includes-no", [1, 2].includes(3))
console.log("parseint-hex", parseInt("0x1F", 16))
console.log("parseint-auto", parseInt("0x1F"))
console.log("parseint-junk", parseInt("12px"))
console.log("parseint-neg", parseInt("-0x10", 16))
console.log("tofixed", (2.5).toFixed(0))
console.log("tofixed-neg", (-2.5).toFixed(0))
console.log("tofixed-pi", (3.14159).toFixed(2))
// -0 ToString drops the sign (`String(-0) === "0"`); the console *inspect* form keeps it.
console.log("negzero-tostring", (-0).toString())
console.log("negzero-string", String(-0))
console.log("negzero-concat", "" + (-0))
console.log("negzero-template", `${-0}`)
console.log("negzero-inspect", -0)
console.log("cpat", "abc".codePointAt(0), "abc".codePointAt(2))
console.log("substr", "hello".substr(1, 3), "hello".substr(-2))
console.log("from-str", Array.from("abc").join(","))
console.log("from-set", Array.from(new Set([1,1,2,3])).join(","))
console.log("from-len", Array.from({length: 3}, (x, i) => i * 10).join(","))
console.log("from-map", Array.from([1,2,3], x => x * 2).join(","))
console.log("rep-amp", "a-b-c".replace("-", "[$&]"), "a-b-c".replaceAll("-", "[$&]"))
console.log("rep-ctx", "abc".replace("b", "$`"), "abc".replace("b", "$'"), "abc".replace("b", "$$"))
console.log("clz32", Math.clz32(1), Math.clz32(0), Math.clz32(0xffffffff))
console.log("fround", Math.fround(1.1), Math.fround(5.5))
console.log("expm1", Math.expm1(0), Math.log1p(0))
console.log("gopn", Object.getOwnPropertyNames({a: 1, b: 2}).join(","))
