// #247 cross-backend built-in divergences (Math round/min/max/hypot, parseInt radix, includes(NaN),
// toFixed) — fixed to match the JS target. interp/vm/native/cranelift/node must all agree. Valid in
// tish and node. (-0 toString and instanceof/at/findLast tracked separately.)
console.log("round-neg", Math.round(-2.5))
console.log("round-pos", Math.round(2.5))
console.log("round-half", Math.round(0.5))
console.log("min-empty", Math.min())
console.log("max-empty", Math.max())
console.log("min-nan", Math.min(1, 0 / 0))
console.log("min-vals", Math.min(3, 1, 2))
console.log("max-vals", Math.max(3, 1, 2))
console.log("hypot", Math.hypot(3, 4))
console.log("atan2", Math.atan2(1, 1))
console.log("includes-nan", [1, 0 / 0].includes(0 / 0))
console.log("includes-no", [1, 2].includes(3))
console.log("parseint-hex", parseInt("0x1F", 16))
console.log("parseint-auto", parseInt("0x1F"))
console.log("parseint-junk", parseInt("12px"))
console.log("parseint-neg", parseInt("-0x10", 16))
console.log("tofixed", (2.5).toFixed(0))
console.log("tofixed-neg", (-2.5).toFixed(0))
console.log("tofixed-pi", (3.14159).toFixed(2))
