#!/usr/bin/env python3
"""Generate tests/main.tish and tests/main.js — one bundled perf suite for CI (single native link per backend).

Includes every tests/core + tests/modules workload that has a matching .js/.mjs and no top-level `import`
(so rust/cranelift/llvm/wasi native builds succeed). Same set as run_performance_manual.sh minus
recursion_stress and minus files that import tish:http/fs/process.

Re-run after adding/removing paired pure tests:
  python3 scripts/generate_perf_ci_main.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TESTS = REPO / "tests"
CORE = TESTS / "core"
MODULES = TESTS / "modules"


def js_path_for(tish: Path) -> Path | None:
    stem = tish.stem
    d = tish.parent
    mjs = d / f"{stem}.mjs"
    if mjs.is_file():
        return mjs
    js = d / f"{stem}.js"
    if js.is_file():
        return js
    return None


def has_file_import(tish: Path) -> bool:
    text = tish.read_text(encoding="utf-8")
    return bool(re.search(r"^import\s+", text, re.MULTILINE))


def collect() -> list[tuple[Path, Path]]:
    pairs: list[tuple[Path, Path]] = []
    for d in (CORE, MODULES):
        if not d.is_dir():
            continue
        for tish in sorted(d.glob("*.tish")):
            if tish.stem == "recursion_stress":
                continue
            js = js_path_for(tish)
            if js is None:
                continue
            if has_file_import(tish):
                continue
            pairs.append((tish, js))
    pairs.sort(key=lambda p: str(p[0]))
    return pairs


def tish_key(tish: Path) -> str:
    rel = tish.relative_to(TESTS)
    return str(rel).replace("/", "_").replace(".tish", "")


def emit_tish(pairs: list[tuple[Path, Path]]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/generate_perf_ci_main.py — do not edit by hand.",
        "// Bundled perf suite: one binary per native backend in CI (see scripts/run_performance_suite.sh).",
        "",
    ]
    for tish, _js in pairs:
        key = tish_key(tish)
        body = tish.read_text(encoding="utf-8").rstrip() + "\n"
        lines.append(f"fn __perf_run_{key}() {{")
        for line in body.splitlines():
            lines.append("\t" + line if line else "")
        lines.append("}")
        lines.append(f"__perf_run_{key}()")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def emit_js(pairs: list[tuple[Path, Path]]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/generate_perf_ci_main.py — do not edit by hand.",
        "",
    ]
    for _tish, js in pairs:
        body = js.read_text(encoding="utf-8").rstrip() + "\n"
        lines.append("{")
        for line in body.splitlines():
            lines.append("  " + line if line else "")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    pairs = collect()
    if not pairs:
        print("No paired pure tests found", file=sys.stderr)
        return 1
    tish_out = TESTS / "main.tish"
    js_out = TESTS / "main.js"
    tish_out.write_text(emit_tish(pairs), encoding="utf-8")
    js_out.write_text(emit_js(pairs), encoding="utf-8")
    print(f"Wrote {len(pairs)} tests -> {tish_out.relative_to(REPO)} and {js_out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
