#!/usr/bin/env bash
# Generate tests/main.tish and tests/main.js — bundled perf suite for CI (one native link per backend).
#
# Includes tests/core + tests/modules *.tish with matching .mjs or .js, excluding recursion_stress and
# any file whose first-column line starts with "import " (native http/fs/process imports).
#
# Usage:
#   ./scripts/generate_perf_ci_main.sh           # write tests/main.tish + tests/main.js
#   ./scripts/generate_perf_ci_main.sh --list-pairs   # tab: tish_path<TAB>js_path (repo-relative)

set -euo pipefail
cd "$(dirname "$0")/.."

list_pairs_to_stdout() {
  local d tish base js
  for d in tests/core tests/modules; do
    [[ -d "$d" ]] || continue
    for tish in "$d"/*.tish; do
      [[ -f "$tish" ]] || continue
      base=$(basename "$tish" .tish)
      [[ "$base" == "recursion_stress" ]] && continue
      js=""
      if [[ -f "$d/${base}.mjs" ]]; then
        js="$d/${base}.mjs"
      elif [[ -f "$d/${base}.js" ]]; then
        js="$d/${base}.js"
      else
        continue
      fi
      if grep -q '^import[[:space:]]' "$tish" 2>/dev/null; then
        continue
      fi
      printf '%s\t%s\n' "$tish" "$js"
    done
  done | LC_ALL=C sort -t "$(printf '\t')" -k1,1
}

tish_key_from_path() {
  local rel="${1#tests/}"
  rel="${rel%.tish}"
  echo "${rel//\//_}"
}

emit_main_tish() {
  local out="$1" pairs="$2"
  {
    echo "// AUTO-GENERATED by scripts/generate_perf_ci_main.sh — do not edit by hand."
    echo "// Bundled perf suite: one binary per native backend in CI (see scripts/run_performance_suite.sh)."
    echo ""
  } >"$out"
  while IFS="$(printf '\t')" read -r tish js; do
    [[ -n "${tish:-}" ]] || continue
    local key
    key=$(tish_key_from_path "$tish")
    {
      echo "fn __perf_run_${key}() {"
      while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ -n "$line" ]]; then
          printf '\t%s\n' "$line"
        else
          printf '\n'
        fi
      done <"$tish"
      echo "}"
      echo "__perf_run_${key}()"
      echo ""
    } >>"$out"
  done <"$pairs"
}

emit_main_js() {
  local out="$1" pairs="$2"
  {
    echo "// AUTO-GENERATED by scripts/generate_perf_ci_main.sh — do not edit by hand."
    echo ""
  } >"$out"
  while IFS="$(printf '\t')" read -r tish js; do
    [[ -n "${js:-}" ]] || continue
    echo "{" >>"$out"
    while IFS= read -r line || [[ -n "$line" ]]; do
      if [[ -n "$line" ]]; then
        printf '  %s\n' "$line" >>"$out"
      else
        printf '\n' >>"$out"
      fi
    done <"$js"
    echo "}" >>"$out"
    echo "" >>"$out"
  done <"$pairs"
}

if [[ "${1:-}" == "--list-pairs" ]]; then
  list_pairs_to_stdout
  exit 0
fi

pairs_tmp=$(mktemp)
trap 'rm -f "$pairs_tmp"' EXIT
list_pairs_to_stdout >"$pairs_tmp"
if [[ ! -s "$pairs_tmp" ]]; then
  echo "No paired pure tests found" >&2
  exit 1
fi

emit_main_tish "tests/main.tish" "$pairs_tmp"
emit_main_js "tests/main.js" "$pairs_tmp"
n=$(wc -l <"$pairs_tmp" | tr -d ' ')
echo "Wrote $n tests -> tests/main.tish and tests/main.js"
